#!/bin/bash

# JPad Cloud Sync Setup Script
# This script helps you configure WebDAV sync with your Synology NAS

echo "================================"
echo "JPad Cloud Sync Setup"
echo "================================"
echo ""

# Check if .env exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

echo "Please enter your Synology WebDAV details:"
echo ""

# Get WebDAV URL
read -p "WebDAV Server URL (e.g., https://192.168.1.100:5006): " webdav_url

# Get username
read -p "Username: " username

# Get password (hidden input)
read -sp "Password: " password
echo ""

# Get remote path
read -p "Remote Path (default: /jpad-notes): " remote_path
remote_path=${remote_path:-/jpad-notes}

# Get sync interval
read -p "Auto-sync interval in seconds (default: 300, 0 to disable): " sync_interval
sync_interval=${sync_interval:-300}

# Create .env file
cat > .env << EOF
# Cloud Sync Configuration
# Generated by setup-sync.sh on $(date)

# WebDAV Server URL (e.g., https://your-synology.com:5006)
VITE_WEBDAV_URL=$webdav_url

# WebDAV Username
VITE_WEBDAV_USERNAME=$username

# WebDAV Password
VITE_WEBDAV_PASSWORD=$password

# Sync folder path on WebDAV server
VITE_WEBDAV_PATH=$remote_path

# Auto-sync interval in seconds (0 to disable auto-sync)
VITE_SYNC_INTERVAL=$sync_interval
EOF

echo ""
echo "✅ Configuration saved to .env"
echo ""
echo "Next steps:"
echo "1. Restart JPad to load the new configuration"
echo "2. Open Settings → Cloud Sync"
echo "3. Click 'Save & Connect' to test the connection"
echo "4. Click 'Sync Now' to start syncing"
echo ""
echo "⚠️  Security Note:"
echo "The .env file contains your password in plain text."
echo "Make sure it's not committed to version control (it's in .gitignore)."
echo ""
echo "For more information, see SYNC_SETUP.md"
