# JPad Cloud Sync Setup Script (PowerShell)
# This script helps you configure WebDAV sync with your Synology NAS

Write-Host "================================" -ForegroundColor Cyan
Write-Host "JPad Cloud Sync Setup" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env exists
if (Test-Path .env) {
    Write-Host "⚠️  .env file already exists!" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -notmatch '^[Yy]$') {
        Write-Host "Setup cancelled." -ForegroundColor Red
        exit 0
    }
}

Write-Host "Please enter your Synology WebDAV details:" -ForegroundColor Green
Write-Host ""

# Get WebDAV URL
$webdav_url = Read-Host "WebDAV Server URL (e.g., https://192.168.1.100:5006)"

# Get username
$username = Read-Host "Username"

# Get password (secure input)
$password_secure = Read-Host "Password" -AsSecureString
$password = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($password_secure)
)

# Get remote path
$remote_path = Read-Host "Remote Path (default: /jpad-notes)"
if ([string]::IsNullOrWhiteSpace($remote_path)) {
    $remote_path = "/jpad-notes"
}

# Get sync interval
$sync_interval = Read-Host "Auto-sync interval in seconds (default: 300, 0 to disable)"
if ([string]::IsNullOrWhiteSpace($sync_interval)) {
    $sync_interval = "300"
}

# Create .env file
$env_content = @"
# Cloud Sync Configuration
# Generated by setup-sync.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# WebDAV Server URL (e.g., https://your-synology.com:5006)
VITE_WEBDAV_URL=$webdav_url

# WebDAV Username
VITE_WEBDAV_USERNAME=$username

# WebDAV Password
VITE_WEBDAV_PASSWORD=$password

# Sync folder path on WebDAV server
VITE_WEBDAV_PATH=$remote_path

# Auto-sync interval in seconds (0 to disable auto-sync)
VITE_SYNC_INTERVAL=$sync_interval
"@

$env_content | Out-File -FilePath .env -Encoding UTF8

Write-Host ""
Write-Host "✅ Configuration saved to .env" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Restart JPad to load the new configuration"
Write-Host "2. Open Settings → Cloud Sync"
Write-Host "3. Click 'Save & Connect' to test the connection"
Write-Host "4. Click 'Sync Now' to start syncing"
Write-Host ""
Write-Host "⚠️  Security Note:" -ForegroundColor Yellow
Write-Host "The .env file contains your password in plain text."
Write-Host "Make sure it's not committed to version control (it's in .gitignore)."
Write-Host ""
Write-Host "For more information, see SYNC_SETUP.md" -ForegroundColor Cyan
